apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: final_assignment-backend  # The local image
        imagePullPolicy: Never  # Avoid pulling from Docker Hub, use the local image
        ports:
        - containerPort: 8000  # The container exposes port 8000 (as per docker-compose)
        env:
        - name: DB_ADDRESS
          value: "postgres"  # The address of the Postgres service (name of the service in K8s)
        - name: DB_USERNAME
          value: "postgres"  # The username for the DB
        - name: DB_NAME
          value: "postgres"  # The DB name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password  # Referencing the secret for DB password
              key: db-password   # The key inside the secret
---
